export type Role = "user" | "assistant" | "tool" | "system";

/** "trace" rows are intermediate agent breadcrumbs (tool-call hints,
 * progress pings) that should not be rendered as conversational replies. */
export type MessageKind = "message" | "trace";

/** Tool call details. */
export interface UIToolCall {
  id: string;
  name: string;
  args: Record<string, unknown>;
  result?: string;
  success?: boolean;
}

/** One image attached to a UIMessage.
 *
 * ``url`` can arrive in three different shapes, which the bubble renders
 * identically:
 * - A ``data:image/...;base64,...`` URL generated by the Composer for the
 *   optimistic preview of an in-flight user turn. Self-contained, no
 *   lifecycle.
 * - A signed ``/api/media/...`` URL attached to a historical user turn by
 *   the backend on session replay. Safe to drop into an ``<img src>``.
 * - Absent. The backend couldn't resolve a stored path (file moved,
 *   deleted, or pre-media-persistence session). The bubble shows a
 *   placeholder tile with ``name`` as the label.
 */
export interface UIImage {
  url?: string;
  name?: string;
}

export type UIMediaKind = "image" | "video" | "file";

export interface UIMediaAttachment {
  kind: UIMediaKind;
  url?: string;
  name?: string;
}

export interface UIMessage {
  id: string;
  role: Role;
  content: string;
  kind?: MessageKind;
  isStreaming?: boolean;
  createdAt: number;
  /** For assistant: captured reasoning/thinking content. */
  reasoning?: string;
  /** For assistant: tool calls made during this turn. */
  toolCalls?: UIToolCall[];
  /** For trace rows: each individual hint line, so consecutive hints can
   * render as a single collapsible group. */
  traces?: string[];
  /** User turn: optimistic blob URLs for preview. Replay: placeholder chips. */
  images?: UIImage[];
  /** Signed or local UI-renderable media attachments. */
  media?: UIMediaAttachment[];
  /** Optional answer choices for a pending ask_user question. */
  buttons?: string[][];
}

export interface ChatSummary {
  /** Server-side session key, e.g. ``websocket:abcd-...`` or ``remote:abcd-...``. */
  key: string;
  /** Local channel + chat_id parts derived from ``key`` for convenience. */
  channel: string;
  chatId: string;
  createdAt: string | null;
  updatedAt: string | null;
  preview: string;
  /** Session source: "local" or "remote" */
  source?: "local" | "remote";
  /** Remote session status */
  status?: string;
  /** Session title (for remote sessions) */
  title?: string;
}

export interface BootstrapResponse {
  token: string;
  ws_path: string;
  expires_in: number;
  model_name?: string | null;
}

export interface SettingsPayload {
  agent: {
    model: string;
    provider: string;
    resolved_provider: string | null;
    has_api_key: boolean;
  };
  providers: Array<{
    name: string;
    label: string;
  }>;
  runtime: {
    config_path: string;
  };
  requires_restart: boolean;
}

export interface SettingsUpdate {
  model?: string;
  provider?: string;
}

// ── Model Picker types ──────────────────────────────────────────────────
export interface ModelInfo {
  id: string;
  name: string;
  provider: string;
  family: string;
  capabilities: {
    reasoning: boolean;
    vision: boolean;
    tool_call: boolean;
  };
}

export interface ProviderInfo {
  provider_id: string;
  sdk_mode: string;
  default_model: string;
  enabled: boolean;
  models: string[];
  has_api_key: boolean;
  base_url: string;
}

// ── MCP types ──────────────────────────────────────────────────────────
export interface MCPServerInfo {
  name: string;
  command: string;
  transport: string;
  disabled: boolean;
  lifecycle: string;
  connected: boolean;
  tool_count: number;
}

export interface MCPToolInfo {
  name: string;
  server: string;
  description?: string;
  input_schema?: Record<string, unknown>;
}

// ── Heartbeat types ─────────────────────────────────────────────────────
export interface HeartbeatStatus {
  enabled: boolean;
  interval: string;
  is_running: boolean;
  last_run: string | null;
  last_result: string | null;
  heartbeat_file: string;
  has_heartbeat_file: boolean;
}

// ── Rewind types ────────────────────────────────────────────────────────
export interface Checkpoint {
  index: number;
  content: string;
  timestamp: string;
  has_file_changes: boolean;
}

export interface RewindResponse {
  success: boolean;
  rewound_to: number;
  message_content: string;
}

// ── Voice types ─────────────────────────────────────────────────────────
export interface VoiceTranscribeResponse {
  success: boolean;
  text: string;
  note?: string;
}

// ── Feedback types ──────────────────────────────────────────────────────
export interface FeedbackSubmit {
  rating: number;
  message?: string;
  page?: string;
}

// ── Debug types ─────────────────────────────────────────────────────────
export interface DebugLogEntry {
  timestamp: string;
  level: string;
  message: string;
}

export interface DebugCommandResult {
  output: string;
  success: boolean;
}

// ── Context / Token Usage types ────────────────────────────────────────
export interface TokenUsage {
  prompt_tokens?: number;
  completion_tokens?: number;
  total_tokens?: number;
}

export interface ContextUsage {
  usage: TokenUsage;
  limits: { context: number; output: number };
  model: string;
  message_count: number;
}

// ── Connector types ────────────────────────────────────────────────────
export interface ConnectorInfo {
  id: string;
  display_name: string;
  auth_type: string;
  connected: boolean;
  auth_configured: boolean;
  sync_state: string;
}

// ── Safety Profile types ────────────────────────────────────────────────
export interface SafetyProfile {
  id: number;
  name: string;
  desc: string;
  bypass: boolean;
  code: string;
  files: string;
  dangerous: string;
}

export type ConnectionStatus =
  | "idle"
  | "connecting"
  | "open"
  | "reconnecting"
  | "closed"
  | "error";

export type InboundEvent =
  | { event: "ready"; chat_id: string; client_id: string }
  | { event: "attached"; chat_id: string; session_id?: string }
  | {
      event: "message";
      chat_id: string;
      text: string;
      reply_to?: string;
      media?: string[];
      media_urls?: Array<{ url: string; name?: string }>;
      buttons?: string[][];
      /** Original prompt before the websocket text fallback appends buttons. */
      button_prompt?: string;
      /** Present when the frame is an agent breadcrumb (e.g. tool hint,
       * generic progress line) rather than a conversational reply. */
      kind?: "tool_hint" | "progress";
    }
  | {
      event: "delta";
      chat_id: string;
      text: string;
      stream_id?: string;
    }
  | {
      event: "stream_end";
      chat_id: string;
      stream_id?: string;
    }
  | { event: "turn_end"; chat_id: string }
  | { event: "error"; chat_id?: string; detail?: string }
  | { event: "reasoning"; chat_id: string; text: string }
  | { event: "reasoning_end"; chat_id: string }
  | {
      event: "tool_call";
      chat_id: string;
      tool_name: string;
      tool_args: Record<string, unknown>;
    }
  | {
      event: "tool_result";
      chat_id: string;
      tool_name: string;
      result: string;
      success: boolean;
    }
  | {
      event: "user_input";
      chat_id: string;
      question: string;
      options?: string[];
    }
  | {
      event: "approval_request";
      chat_id: string;
      tool_name: string;
      tool_args: Record<string, unknown>;
      required_permissions: string[];
      tool_call_id: string;
    };

/** Base64-encoded image attached to an outbound ``message`` envelope.
 *
 * ``data_url`` must be a ``data:image/<png|jpeg|webp|gif>;base64,...`` string
 * â€” the server whitelists those MIME types and rejects everything else
 * (including SVG, to avoid an XSS surface). ``name`` is advisory: it's
 * preserved for the file on disk and surfaced as the placeholder label when
 * the session is replayed.
 */
export interface OutboundMedia {
  data_url: string;
  name?: string;
}

export type Outbound =
  | { type: "new_chat" }
  | { type: "attach"; chat_id: string }
  | {
      type: "message";
      chat_id: string;
      content: string;
      media?: OutboundMedia[];
    }
  | {
      type: "approval_response";
      chat_id: string;
      tool_call_id: string;
      approved: boolean;
      always_allow?: boolean;
    };
