"""Event system for JARVIS - pub/sub event bus and lifecycle hooks"""

from jarvis.core.events.bus import EventBus
from jarvis.core.events.hooks import HookContext, HookRegistry, HookResult, HookStage
from jarvis.core.events.types import (
    AgentEnded,
    AgentError,
    AgentEvent,
    AgentStarted,
    ExtensionError,
    ExtensionEvent,
    ExtensionLoaded,
    ExtensionUnloaded,
    MessageComplete,
    MessageDelta,
    MessageEvent,
    ProgressEvent,
    ProgressUpdated,
    SessionEvent,
    SessionShutdown,
    SessionStarted,
    SkillActivated,
    SkillDeactivated,
    StatusEvent,
    StatusUpdated,
    SystemEvent,
    SystemWarning,
    ThinkingDelta,
    ToolCallEnded,
    ToolCallError,
    ToolCallStarted,
    ToolEvent,
    TurnEnded,
    TurnEvent,
    TurnStarted,
)

__all__ = [
    "EventBus",
    "HookContext",
    "HookRegistry",
    "HookResult",
    "HookStage",
    # Events
    "AgentEvent",
    "AgentStarted",
    "AgentEnded",
    "AgentError",
    "ExtensionEvent",
    "ExtensionLoaded",
    "ExtensionUnloaded",
    "ExtensionError",
    "MessageEvent",
    "MessageDelta",
    "MessageComplete",
    "ThinkingDelta",
    "ProgressEvent",
    "ProgressUpdated",
    "SessionEvent",
    "SessionStarted",
    "SessionShutdown",
    "SkillActivated",
    "SkillDeactivated",
    "StatusEvent",
    "StatusUpdated",
    "SystemEvent",
    "SystemWarning",
    "ToolEvent",
    "ToolCallStarted",
    "ToolCallEnded",
    "ToolCallError",
    "TurnEvent",
    "TurnStarted",
    "TurnEnded",
]
