"""Event system for JARVIS - pub/sub event bus and lifecycle hooks"""

from core.events.bus import EventBus
from core.events.hooks import HookContext, HookRegistry, HookResult, HookStage
from core.events.types import (
    AgentEvent,
    AgentStarted,
    AgentEnded,
    AgentError,
    ExtensionEvent,
    ExtensionLoaded,
    ExtensionUnloaded,
    ExtensionError,
    MessageEvent,
    MessageDelta,
    MessageComplete,
    ThinkingDelta,
    ProgressEvent,
    ProgressUpdated,
    SessionEvent,
    SessionStarted,
    SessionShutdown,
    SkillActivated,
    SkillDeactivated,
    StatusEvent,
    StatusUpdated,
    SystemEvent,
    SystemWarning,
    ToolEvent,
    ToolCallStarted,
    ToolCallEnded,
    ToolCallError,
    TurnEvent,
    TurnStarted,
    TurnEnded,
)

__all__ = [
    "EventBus",
    "HookContext",
    "HookRegistry",
    "HookResult",
    "HookStage",
    # Events
    "AgentEvent",
    "AgentStarted",
    "AgentEnded",
    "AgentError",
    "ExtensionEvent",
    "ExtensionLoaded",
    "ExtensionUnloaded",
    "ExtensionError",
    "MessageEvent",
    "MessageDelta",
    "MessageComplete",
    "ThinkingDelta",
    "ProgressEvent",
    "ProgressUpdated",
    "SessionEvent",
    "SessionStarted",
    "SessionShutdown",
    "SkillActivated",
    "SkillDeactivated",
    "StatusEvent",
    "StatusUpdated",
    "SystemEvent",
    "SystemWarning",
    "ToolEvent",
    "ToolCallStarted",
    "ToolCallEnded",
    "ToolCallError",
    "TurnEvent",
    "TurnStarted",
    "TurnEnded",
]
