"""Event type definitions for JARVIS event system"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


# ---------------------------------------------------------------------------
# Agent Lifecycle Events
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class AgentEvent:
    """Base class for all agent lifecycle events"""
    timestamp: float
    agent_name: str = ""


@dataclass(frozen=True)
class AgentStarted(AgentEvent):
    """Emitted when the agent begins processing"""
    input: str = ""


@dataclass(frozen=True)
class AgentEnded(AgentEvent):
    """Emitted when the agent finishes processing"""
    output: str = ""


@dataclass(frozen=True)
class AgentError(AgentEvent):
    """Emitted when the agent encounters an error"""
    error: str = ""
    recoverable: bool = False


# ---------------------------------------------------------------------------
# Turn Events
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class TurnEvent:
    """Base class for turn lifecycle events"""
    timestamp: float
    turn_number: int = 0


@dataclass(frozen=True)
class TurnStarted(TurnEvent):
    """Emitted at the start of each LLM request cycle"""
    pass


@dataclass(frozen=True)
class TurnEnded(TurnEvent):
    """Emitted when a turn completes with assistant message and tool results"""
    tool_count: int = 0


# ---------------------------------------------------------------------------
# Message / Streaming Events
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class MessageEvent:
    """Base class for message streaming events"""
    timestamp: float


@dataclass(frozen=True)
class MessageDelta(MessageEvent):
    """Emitted for every chunk of text generated by the LLM"""
    delta: str = ""
    content_index: int = 0


@dataclass(frozen=True)
class MessageComplete(MessageEvent):
    """Emitted when a full message block is completed"""
    content: str = ""
    content_index: int = 0


@dataclass(frozen=True)
class ThinkingDelta(MessageEvent):
    """Emitted for reasoning/thinking chunks from the LLM"""
    delta: str = ""


# ---------------------------------------------------------------------------
# Tool Execution Events
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ToolEvent:
    """Base class for tool execution events"""
    timestamp: float
    tool_name: str = ""
    tool_call_id: str = ""


@dataclass(frozen=True)
class ToolCallStarted(ToolEvent):
    """Emitted before a tool is executed"""
    args: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class ToolCallEnded(ToolEvent):
    """Emitted after a tool completes"""
    result: Any = None
    duration_ms: float = 0.0
    success: bool = True


@dataclass(frozen=True)
class ToolCallError(ToolEvent):
    """Emitted when a tool execution fails"""
    error: str = ""
    duration_ms: float = 0.0


# ---------------------------------------------------------------------------
# Session Events
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class SessionEvent:
    """Base class for session lifecycle events"""
    timestamp: float
    session_id: str = ""


@dataclass(frozen=True)
class SessionStarted(SessionEvent):
    """Emitted when a new session begins"""
    model: str = ""
    cwd: str = ""


@dataclass(frozen=True)
class SessionShutdown(SessionEvent):
    """Emitted before a session is closed"""
    reason: str = ""


@dataclass(frozen=True)
class SkillActivated(SessionEvent):
    """Emitted when a skill is activated"""
    skill_name: str = ""


@dataclass(frozen=True)
class SkillDeactivated(SessionEvent):
    """Emitted when a skill is deactivated"""
    skill_name: str = ""


# ---------------------------------------------------------------------------
# Extension Events
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ExtensionEvent:
    """Base class for extension lifecycle events"""
    timestamp: float
    extension_name: str = ""


@dataclass(frozen=True)
class ExtensionLoaded(ExtensionEvent):
    """Emitted when an extension is successfully loaded"""
    version: str = ""
    tools_count: int = 0


@dataclass(frozen=True)
class ExtensionUnloaded(ExtensionEvent):
    """Emitted when an extension is unloaded"""
    reason: str = ""


@dataclass(frozen=True)
class ExtensionError(ExtensionEvent):
    """Emitted when an extension encounters an error"""
    error: str = ""


# ---------------------------------------------------------------------------
# Status / Progress Events
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class StatusEvent:
    """Base class for status update events"""
    timestamp: float
    message: str = ""


@dataclass(frozen=True)
class StatusUpdated(StatusEvent):
    """Emitted when the agent status changes"""
    status: str = ""


@dataclass(frozen=True)
class ProgressEvent:
    """Base class for progress events"""
    timestamp: float
    task: str = ""


@dataclass(frozen=True)
class ProgressUpdated(ProgressEvent):
    """Emitted to report progress on long-running tasks"""
    progress: float = 0.0  # 0.0 to 1.0


# ---------------------------------------------------------------------------
# System Events
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class SystemEvent:
    """Base class for system-level events"""
    timestamp: float


@dataclass(frozen=True)
class SystemWarning(SystemEvent):
    """Emitted for non-fatal warnings (e.g., config issues)"""
    message: str = ""
    source: str = ""
